/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Persistencia.Fachada_Persistencia;
import dominio.Animal;
import dominio.Corral;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Listados extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listados
     */
    public Listados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnListarCorral = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarCorral = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnListarAnimal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListadoAnimal = new javax.swing.JTable();

        setBackground(java.awt.Color.lightGray);
        setClosable(true);
        setMaximumSize(new java.awt.Dimension(670, 500));
        setMinimumSize(new java.awt.Dimension(670, 500));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(670, 500));

        jPanel1.setBackground(java.awt.Color.lightGray);

        btnListarCorral.setText("Listar");
        btnListarCorral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCorralActionPerformed(evt);
            }
        });

        tblListarCorral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Capacidad", "Observaciones", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblListarCorral);
        tblListarCorral.getColumnModel().getColumn(0).setMinWidth(50);
        tblListarCorral.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblListarCorral.getColumnModel().getColumn(0).setMaxWidth(50);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnListarCorral, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnListarCorral, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Corral", jPanel1);

        btnListarAnimal.setText("Listar");
        btnListarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarAnimalActionPerformed(evt);
            }
        });

        tblListadoAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nro Caravana", "Peso Actual", "Estado", "Productor"
            }
        ));
        jScrollPane2.setViewportView(tblListadoAnimal);
        tblListadoAnimal.getColumnModel().getColumn(0).setMinWidth(50);
        tblListadoAnimal.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblListadoAnimal.getColumnModel().getColumn(0).setMaxWidth(50);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnListarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnListarAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Animal", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarCorralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCorralActionPerformed

        listar(Corral.class, tblListarCorral, mdl_corral);
    }//GEN-LAST:event_btnListarCorralActionPerformed

    private void btnListarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAnimalActionPerformed
        listar(Animal.class, tblListadoAnimal, mdl_animal);
    }//GEN-LAST:event_btnListarAnimalActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarAnimal;
    private javax.swing.JButton btnListarCorral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblListadoAnimal;
    private javax.swing.JTable tblListarCorral;
    // End of variables declaration//GEN-END:variables
    static EntityManagerFactory emf = Persistence.createEntityManagerFactory("SiggPU");
    DefaultTableModel mdl_corral = new DefaultTableModel(new String[]{"ID", "Nombre", "Capacidad", "Observaciones", "Estado"}, 0);
    DefaultTableModel mdl_animal = new DefaultTableModel(new String[]{"ID", "Nro Caravana", "Peso actual", "Estado", "Productor"}, 0);

    public void listar(Object obj, JTable t, DefaultTableModel d) {
        EntityManager em = emf.createEntityManager();
        limpiar_tabla(d);
        List<Object> lista = null;
        t.setModel(d);
        t.getColumnModel().getColumn(0).setMaxWidth(30);
        if (obj == Corral.class) {
            lista = Fachada_Persistencia.getInstancia().listar(Corral.class);
            for (Object o : lista) {
                Corral c = (Corral) o;
                d.addRow(new Object[]{c.getId(), c.getNombre(), c.getCapacidad(), c.getObservaciones(), c.getEstado()});
            }
        } else if (obj == Animal.class) {
            lista = Fachada_Persistencia.getInstancia().listar(Animal.class);
            for (Object o : lista) {
                Animal a = (Animal) o;
                d.addRow(new Object[]{a.getId(), a.getNroCaravana(), a.getPesoActual(), a.getEstado(), a.getProductor().getNombre()});
            }
        }
    }

    private void limpiar_tabla(DefaultTableModel d) {
        while (d.getRowCount() > 0) {
            d.removeRow(0);
        }

    }
}
